name = "athene-ai"
main = "src/worker.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "JOURNAL_KV"
id = ""

[[r2_buckets]]
binding = 'JOURNAL_AUDIO'
bucket_name = 'journal-audio'

[observability]
enabled = true
